export const siteConfig = {
  siteName: "WerkCV",
  domain: "werkcv.be",
  baseUrl: "https://werkcv.be",
  nlSiteUrl: "https://werkcv.nl",
  country: "België",
  countryCode: "BE",
  language: "nl-BE",
  locale: "nl_BE",
  hreflang: "nl-BE",
  currency: "EUR",
  price: 4.99,
  defaultLocale: "nl",
  targetRegion: "Vlaanderen en heel België",
  jobBoards: ["jobat.be", "stepstone.be", "vdab.be", "linkedin.be"],
  competitorNote: "Geen abonnement. Eenmalige betaling.",
  googleSiteVerification: "",
  metaAuthor: "WerkCV",
  contactEmail: "contact@werkcv.be",
  rssUrl: "https://werkcv.be/rss.xml",
  twitterSite: "@werkcvnl",
  homeAlternates: {
    "nl-BE": "https://werkcv.be/",
    "nl-NL": "https://werkcv.nl/",
  },
} as const;
